//! Axiom Engram - Persistent experience-based memory system
//! 
//! Three layers:
//! - Episodic: direct experiences, on-device, user-owned
//! - Semantic: abstractions distilled nightly  
//! - Imagined: generated by imagination engine, quarantined from real engrams

pub mod schema;
pub mod store;
pub mod engram;

pub use engram::{Engram, EngramLayer, EngramSource, EngramLink, PrivacyLevel, CoherenceState, Goal, ConsolidationRun};
pub use store::EngramStore;
pub use store::TemporalPattern;
pub use schema::create_tables;
pub use thiserror::Error;

#[derive(Error, Debug)]
pub enum EngramError {
    #[error("Database error: {0}")]
    Database(#[from] rusqlite::Error),
    #[error("Serialization error: {0}")]
    Serialization(#[from] serde_json::Error),
    #[error("Not found: {0}")]
    NotFound(String),
    #[error("Validation error: {0}")]
    Validation(String),
}

/// Result type for engram operations
pub type Result<T> = std::result::Result<T, EngramError>;